# Generated by Django 2.2.dev20180914183443 on 2019-01-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'uzytkownik', 'verbose_name_plural': 'uzytkownicy'},
        ),
    ]
