# Generated by Django 2.2.dev20180914183443 on 2019-01-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190115_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_account', 'Może przeglądać konto'), ('view_wallet', 'Może przeglądać portfel'), ('add_wallet', 'Może doladowywac portfel'), ('transfer_wallet', 'Może przekazywac pieniadze'), ('view_myshopping', 'Może przeglądać swoje zakupy')), 'verbose_name': 'Uzytkownik', 'verbose_name_plural': 'Uzytkownicy'},
        ),
    ]
