# Generated by Django 2.2.dev20180914183443 on 2019-01-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190122_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_account', 'Może przeglądać konto'), ('view_wallet', 'Może przeglądać portfel'), ('add_wallet', 'Może doladowywac portfel'), ('transfer_wallet', 'Może przekazywac pieniadze'), ('view_myshopping', 'Może przeglądać swoje zakupy'), ('test_test', 'Testowy')), 'verbose_name': 'Uzytkownik', 'verbose_name_plural': 'Uzytkownicy'},
        ),
    ]
