# Generated by Django 2.2.dev20180914183443 on 2019-02-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mytoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyToken',
        ),
    ]
