# Generated by Django 2.2.dev20180914183443 on 2019-03-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mygroup',
            options={'verbose_name': 'Grupa', 'verbose_name_plural': 'Grupy'},
        ),
        migrations.AddField(
            model_name='user',
            name='display_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_display_group_set', to='accounts.MyGroup'),
        ),
    ]
