# Generated by Django 2.2.dev20180914183443 on 2019-03-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190307_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
