# Generated by Django 2.2.dev20180914183443 on 2019-03-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190308_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
