# Generated by Django 2.2.dev20180914183443 on 2019-03-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygroup',
            name='title',
            field=models.CharField(default='Użytkownik', max_length=50),
        ),
    ]
