# Generated by Django 2.2.dev20180914183443 on 2019-03-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_mygroup_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mygroup',
            old_name='title',
            new_name='usertitle',
        ),
        migrations.AddField(
            model_name='mygroup',
            name='disporder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mygroup',
            name='showteam',
            field=models.BooleanField(default=False),
        ),
    ]
