# Generated by Django 2.2.dev20180914183443 on 2019-01-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_managers'),
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module',
            new_name='Modules',
        ),
    ]
