# Generated by Django 2.2.dev20180914183443 on 2019-02-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20190116_1826'),
        ('panel', '0002_auto_20190115_2022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modules',
            new_name='Module',
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Panel - Moduł', 'verbose_name_plural': 'Panel - Moduły'},
        ),
    ]
