# Generated by Django 2.2.dev20180914183443 on 2019-01-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nazwa', max_length=64, verbose_name='Nazwa serwera')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner')),
                ('ip', models.CharField(max_length=64, verbose_name='IP')),
                ('port', models.CharField(max_length=64, null=True, verbose_name='Port')),
                ('tag', models.CharField(max_length=64, null=True, verbose_name='Tag serwera')),
            ],
            options={
                'verbose_name': 'Serwer',
                'verbose_name_plural': 'Serwery',
            },
        ),
    ]
