# Generated by Django 2.2.dev20180914183443 on 2019-01-15 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('tag', models.CharField(max_length=512)),
                ('flags', models.CharField(max_length=512)),
                ('description', models.TextField(null=True)),
                ('description_full', models.TextField(null=True)),
                ('servers', models.ManyToManyField(to='servers.Server')),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonusy',
                'db_table': 'shop_bonus',
            },
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=512)),
                ('flags', models.CharField(max_length=512)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
            options={
                'verbose_name': 'Premium',
                'verbose_name_plural': 'Premiums',
                'db_table': 'shop_premium',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
            ],
            options={
                'verbose_name': 'Cena',
                'verbose_name_plural': 'Ceny',
                'db_table': 'shop_price',
            },
        ),
        migrations.CreateModel(
            name='SmsNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat', models.CharField(max_length=512)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('number', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Numer SMS',
                'verbose_name_plural': 'Numery SMS',
                'db_table': 'shop_sms_numbers',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('bonus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Bonus')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Price')),
            ],
            options={
                'verbose_name': 'Usługa',
                'verbose_name_plural': 'Usługi',
                'db_table': 'shop_service',
            },
        ),
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=512)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('read_count', models.IntegerField(default=0)),
                ('multi', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kod promocyjny',
                'verbose_name_plural': 'Kody promocyjne',
                'db_table': 'shop_promotion_code',
            },
        ),
        migrations.CreateModel(
            name='PremiumCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=512)),
                ('flags', models.CharField(max_length=512)),
                ('time', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('premium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Premium')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Service')),
            ],
            options={
                'verbose_name': 'Premium Cache',
                'verbose_name_plural': 'Premiums Cache',
                'db_table': 'shop_premium_cache',
            },
        ),
    ]
