# Generated by Django 2.2.dev20180914183443 on 2019-01-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Usluga', 'verbose_name_plural': 'Uslugi'},
        ),
    ]
