# Generated by Django 2.2.dev20180914183443 on 2019-02-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190115_1941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmsNumbers',
            new_name='SMSNumber',
        ),
    ]
