# Generated by Django 2.2.dev20180914183443 on 2019-03-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_promotionserviceprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='promotion_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
