# Generated by Django 2.2.dev20180914183443 on 2019-03-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_price_promotion_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='promotion_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
