# Generated by Django 2.2.dev20180914183443 on 2019-03-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190310_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='promotion_percent',
        ),
        migrations.AddField(
            model_name='service',
            name='promotion_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
