# Generated by Django 2.2.dev20180914183443 on 2019-03-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190310_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionserviceprice',
            name='new_value',
        ),
        migrations.AlterField(
            model_name='promotionserviceprice',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
