# Generated by Django 2.2.dev20180914183443 on 2019-02-25 13:56

from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0003_auto_20190116_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nick')),
                ('authid', models.CharField(max_length=32, verbose_name='Steam ID')),
                ('ip', models.CharField(max_length=32, null=True, verbose_name='IP')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('ends', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('length', models.IntegerField()),
                ('reason', models.TextField(max_length=500)),
                ('admin', models.IntegerField()),
                ('adminIp', models.CharField(max_length=32)),
                ('ureason', models.IntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
            options={
                'verbose_name': 'SourceBans - Komunikacja',
                'verbose_name_plural': 'SourceBans - Komunikacja',
                'db_table': 'sourcebans_comms',
            },
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nick')),
                ('authid', models.CharField(max_length=32, verbose_name='Steam ID')),
                ('ip', models.CharField(max_length=32, null=True, verbose_name='IP')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('ends', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('length', models.IntegerField()),
                ('reason', models.TextField(max_length=500)),
                ('admin', models.IntegerField()),
                ('adminIp', models.CharField(max_length=32)),
                ('ureason', models.IntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
            options={
                'verbose_name': 'SourceBans - Ban',
                'verbose_name_plural': 'SourceBans - Bany',
                'db_table': 'sourcebans_bans',
            },
        ),
    ]
