# Generated by Django 2.2.dev20180914183443 on 2019-01-15 15:48

from django.db import migrations, models
import django.db.models.deletion
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, null=True, verbose_name='IP')),
                ('authid', models.CharField(max_length=32, verbose_name='Steam ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('ends', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('length', models.IntegerField()),
                ('reason', models.TextField(max_length=500)),
                ('aid', models.IntegerField()),
                ('adminIp', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=4)),
                ('RemovedBy', models.IntegerField()),
                ('RemoveType', models.CharField(max_length=3)),
                ('RemovedOn', models.IntegerField()),
                ('type', models.IntegerField()),
                ('ureason', models.IntegerField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
        ),
        migrations.CreateModel(
            name='Bans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, null=True, verbose_name='IP')),
                ('authid', models.CharField(max_length=32, verbose_name='Steam ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nick')),
                ('created', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('ends', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('length', models.IntegerField()),
                ('reason', models.TextField(max_length=500)),
                ('aid', models.IntegerField()),
                ('adminIp', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=4)),
                ('RemovedBy', models.IntegerField()),
                ('RemoveType', models.CharField(max_length=3)),
                ('RemovedOn', models.IntegerField()),
                ('type', models.IntegerField()),
                ('ureason', models.IntegerField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
            options={
                'verbose_name': 'ban',
                'verbose_name_plural': 'lista banów',
            },
        ),
    ]
