# Generated by Django 2.2.dev20180914183443 on 2019-02-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alerts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alerts',
        ),
    ]
