# Generated by Django 2.2.dev20180914183443 on 2019-02-09 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0003_auto_20190116_1826'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Admin', 'Admin'), ('Junior Admin', 'Junior Admin')], default='Admin', max_length=50, verbose_name='Typ podania')),
                ('name', models.CharField(max_length=50, verbose_name='Imie')),
                ('age', models.PositiveIntegerField(verbose_name='Wiek')),
                ('microphone', models.BooleanField(default=False, verbose_name='Mikrofon')),
                ('reason', models.TextField(verbose_name='Powod')),
                ('experiance', models.TextField(verbose_name='Doswiadczenie')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server', verbose_name='Serwer')),
            ],
            options={
                'verbose_name': 'Podanie',
                'verbose_name_plural': 'Podania',
                'permissions': (('accept_application', 'Może aktywować podania'), ('cancel_application', 'Może odrzucac podania')),
            },
        ),
        migrations.CreateModel(
            name='ApplicationComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner_name', models.CharField(max_length=50, null=True)),
                ('owner_avatar', models.CharField(max_length=255, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_centrum.Application')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Podanie - komentarz',
                'verbose_name_plural': 'Podanie - komentarze',
            },
        ),
    ]
