# Generated by Django 2.2.dev20180914183443 on 2019-01-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jailbreak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sm_admins',
            name='groups',
            field=models.ManyToManyField(to='jailbreak.Sm_Groups'),
        ),
    ]
