# Generated by Django 2.2.dev20180914183443 on 2019-01-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jailbreak', '0002_sm_admins_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sm_groupoverrides',
            options={'verbose_name': 'Sm_GroupOver', 'verbose_name_plural': 'Sm_GroupOvers'},
        ),
        migrations.AlterModelOptions(
            name='sm_overrides',
            options={'verbose_name': 'Overrides', 'verbose_name_plural': 'Overridess'},
        ),
        migrations.AlterModelOptions(
            name='store_equipment',
            options={'verbose_name': 'Store_Equipment', 'verbose_name_plural': 'Store_Equipments'},
        ),
        migrations.AlterModelOptions(
            name='store_items',
            options={'verbose_name': 'StoreItems', 'verbose_name_plural': 'StoreItemss'},
        ),
        migrations.AlterModelOptions(
            name='store_players',
            options={'verbose_name': 'store_players', 'verbose_name_plural': 'store_playerss'},
        ),
        migrations.AlterModelTable(
            name='custom_chatcolors',
            table='custom_chatcolors',
        ),
        migrations.AlterModelTable(
            name='sm_admins',
            table='sm_admins',
        ),
        migrations.AlterModelTable(
            name='sm_groupimmunity',
            table='sm_groups_immunity',
        ),
        migrations.AlterModelTable(
            name='sm_groupoverrides',
            table='sm_groups_overrides',
        ),
        migrations.AlterModelTable(
            name='sm_groups',
            table='sm_groups',
        ),
        migrations.AlterModelTable(
            name='sm_overrides',
            table='sm_overrides',
        ),
        migrations.AlterModelTable(
            name='store_equipment',
            table='store_equipment',
        ),
        migrations.AlterModelTable(
            name='store_items',
            table='store_items',
        ),
        migrations.AlterModelTable(
            name='store_players',
            table='store_players',
        ),
    ]
