# Generated by Django 2.2.dev20180914183443 on 2019-01-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jailbreak', '0003_auto_20190120_1731'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sm_groupoverrides',
            table='sm_group_overrides',
        ),
    ]
