# Generated by Django 2.2.dev20180914183443 on 2019-01-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jailbreak', '0004_auto_20190120_1739'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sm_groupimmunity',
            table='sm_group_immunity',
        ),
    ]
