# Generated by Django 2.2.dev20180914183443 on 2019-02-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jailbreak', '0006_auto_20190120_1852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custom_ChatColors',
            new_name='CustomChatColor',
        ),
        migrations.RenameModel(
            old_name='Sm_Admins',
            new_name='SourceModAdmin',
        ),
        migrations.RenameModel(
            old_name='Sm_Groups',
            new_name='SourceModGroup',
        ),
        migrations.RenameModel(
            old_name='Sm_GroupImmunity',
            new_name='SourceModGroupImmunity',
        ),
        migrations.RenameModel(
            old_name='Sm_GroupOverrides',
            new_name='SourceModGroupOverride',
        ),
        migrations.RenameModel(
            old_name='Sm_Overrides',
            new_name='SourceModOverride',
        ),
        migrations.RenameModel(
            old_name='Store_Equipment',
            new_name='StoreEquipment',
        ),
        migrations.RenameModel(
            old_name='Store_Items',
            new_name='StoreItem',
        ),
        migrations.RenameModel(
            old_name='Store_Players',
            new_name='StorePlayer',
        ),
        migrations.AlterModelOptions(
            name='customchatcolor',
            options={'verbose_name': 'Kolor czatu', 'verbose_name_plural': 'Kolory czatu'},
        ),
        migrations.AlterModelOptions(
            name='sourcemodadmin',
            options={'verbose_name': 'SourceMod - Admin', 'verbose_name_plural': 'SourceMod - Admini'},
        ),
        migrations.AlterModelOptions(
            name='sourcemodgroup',
            options={'verbose_name': 'SourceMod - Grupa', 'verbose_name_plural': 'SourceMod - Grupy'},
        ),
        migrations.AlterModelOptions(
            name='sourcemodgroupimmunity',
            options={'verbose_name': 'SourceMod - Immunitet Grupy', 'verbose_name_plural': 'SourceMod - Immunitet Grup'},
        ),
        migrations.AlterModelOptions(
            name='sourcemodgroupoverride',
            options={'verbose_name': 'SourceMod - Group Override', 'verbose_name_plural': 'SourceMod - Groups Overrides'},
        ),
        migrations.AlterModelOptions(
            name='sourcemodoverride',
            options={'verbose_name': 'SourceMod - Override', 'verbose_name_plural': 'SourceMod - Overrides'},
        ),
        migrations.AlterModelOptions(
            name='storeequipment',
            options={'verbose_name': 'Store - Ekwipunek', 'verbose_name_plural': 'Store - Ekwipunki'},
        ),
        migrations.AlterModelOptions(
            name='storeitem',
            options={'verbose_name': 'Store - Przedmiot', 'verbose_name_plural': 'Store - Przedmity'},
        ),
        migrations.AlterModelOptions(
            name='storeplayer',
            options={'verbose_name': 'Store - Gracz', 'verbose_name_plural': 'Store - Gracze'},
        ),
    ]
