# Generated by Django 2.2.dev20180914183443 on 2019-02-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jailbreak', '0007_auto_20190222_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemodadmin',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups_set', to='jailbreak.SourceModGroup'),
        ),
    ]
